on: [pull_request_review]

jobs:
  build:
    runs-on: ubuntu-latest
    name: AutoLabel
    steps:
    - name: Label test
      uses: hphu3/label-pr@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        approved-label: "LG"
        changes-requested-label: "Reviewed"
        review-label: "review"
        re-review-label: "re-review"
